//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XProjectWPF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectTrackingEntities : DbContext
    {
        public ProjectTrackingEntities()
            : base("name=ProjectTrackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PT_B_Project> PT_B_Project { get; set; }
        public virtual DbSet<PT_B_Project_Agency> PT_B_Project_Agency { get; set; }
        public virtual DbSet<PT_B_Project_Customer> PT_B_Project_Customer { get; set; }
        public virtual DbSet<PT_B_Project_Lab> PT_B_Project_Lab { get; set; }
        public virtual DbSet<PT_B_Project_Other> PT_B_Project_Other { get; set; }
        public virtual DbSet<PT_B_Quotation> PT_B_Quotation { get; set; }
    }
}
