//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_B_Project
    {
        public string Project_No { get; set; }
        public string Quotation_No { get; set; }
        public string Follow_Man { get; set; }
        public string Project_Type { get; set; }
        public string Company_Name { get; set; }
        public string Contact_Man { get; set; }
        public string Tel { get; set; }
        public string Company_Address { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Project_Name { get; set; }
        public string Product_Model { get; set; }
        public string Cycle_Time { get; set; }
        public string Price { get; set; }
        public string Is_Tax { get; set; }
        public Nullable<System.DateTime> Quotation_Date { get; set; }
        public string Account_Receivable { get; set; }
        public string Payment_Receivable { get; set; }
        public string Un_Account_Receivable { get; set; }
        public string Agency_Account_Payable { get; set; }
        public string Agency_Accounts_Prepaid { get; set; }
        public string Un_Agency_Account_Payable { get; set; }
        public string Lab_Account_Payable { get; set; }
        public string Lab_Accounts_Prepaid { get; set; }
        public string Un_Lab_Account_Payable { get; set; }
        public string Other_Account { get; set; }
        public string Other_Pad_Account { get; set; }
        public string Un_Other_Account { get; set; }
        public string Profits { get; set; }
        public string Now_Profits { get; set; }
        public string Pads_Money { get; set; }
        public string Is_Pads { get; set; }
        public string Is_All_Customer { get; set; }
        public string Is_All_Agency { get; set; }
        public string Is_All_Lab { get; set; }
        public string Is_All_Other { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Oper_Time { get; set; }
        public string Bill_Status { get; set; }
    }
}
