//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_B_Quotation
    {
        public string Quotation_No { get; set; }
        public DateTime Quotation_Date { get; set; }
        public string Follow_Man { get; set; }
        public string Product_Model { get; set; }
        public string Project_Name { get; set; }
        public string Price { get; set; }
        public string Is_Tax { get; set; }
        public string Quotation_Type { get; set; }
        public string Cycle_Time { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public string Contact_Man { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Remark { get; set; }
        public string Bill_Status { get; set; }
        public Nullable<System.DateTime> Oper_Time { get; set; }
    }
}
