//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XProjectWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_B_Project_Customer
    {
        public string Customer_Pays_Id { get; set; }
        public string Project_No { get; set; }
        public Nullable<int> Seq_No { get; set; }
        public string Customer_Money { get; set; }
        public string Customer { get; set; }
        public string Customer_Remark { get; set; }
        public Nullable<System.DateTime> Customer_Date { get; set; }
        public string Is_Customer_Inv { get; set; }
        public string Customer_Inv_Price { get; set; }
        public string Customer_Inv_No { get; set; }
        public Nullable<System.DateTime> Customer_Inv_Date { get; set; }
    }
}
